# -*- coding: utf-8 -*-
"""foodie

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pS2cORaKfVewUGrOV6sc7gDwown0yHPD
"""

from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/nycrest.csv'

import pandas as pd
df = pd.read_csv(file_path)

df.head()

df.tail()

df.info()

df.describe()

italian_restaurants = df[df['Catagory'] == 'Italian']

print(italian_restaurants.head())

italian_restaurants['Number of review'] = pd.to_numeric(italian_restaurants['Number of review'], errors='coerce')
italian_restaurants_sorted = italian_restaurants.loc[italian_restaurants['Number of review'].nlargest(N).index]

print(italian_restaurants_sorted)

italian_restaurants_sorted['Number of review'] = pd.to_numeric(italian_restaurants_sorted['Number of review'], errors='coerce')
print(italian_restaurants_sorted['Number of review'].dtype)

italian_restaurants['Number of review'] = pd.to_numeric(italian_restaurants['Number of review'], errors='coerce')
italian_restaurants_sorted = italian_restaurants.loc[italian_restaurants['Number of review'].nlargest(N).index]

# Check the data type of the "Number of review" column
print(italian_restaurants_sorted['Number of review'].dtype)

print(italian_restaurants_sorted)

